name: Branch status check

on:
  push:
    branches: [main, pull-request]
  pull_request:
    branches: [pull-request]

concurrency:
  group: branch-status-check-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  status-check:
    name: status-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run tsc

      - name: Lint
        run: npm run lint

      - name: Static build
        run: npm run build
